### ISSUE TITLE
Duplicate on line 36 in complex-types.d.ts

### ISSUE THREAD

**Issue by o-az** [syntax-tree/mdast-util-mdx-expression#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.2.0

### Steps to reproduce

https://github.com/syntax-tree/mdast-util-mdx-expression/blob/603e8842f535405c00d35c0ad326a4ac8353b382/complex-types.d.ts#L35

![CleanShot 2022-06-03 at 17 38 18](https://user-images.githubusercontent.com/23618431/171963229-b0d098e6-6a4f-410a-8641-aadf0498e224.png)

### Expected behavior

no duplicate

### Actual behavior

duplicate

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Thanks, [released](https://github.com/syntax-tree/mdast-util-mdx-expression/releases/tag/1.2.1)!
